# Generated by Django 4.2.3 on 2023-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('I-YEAR', 'I-year'), ('II-YEAR', 'II-year'), ('III-YEAR', 'III-year'), ('IV-YEAR', 'IV-year')], max_length=100)),
                ('sem', models.CharField(blank=True, choices=[('I-SEM', 'I-sem'), ('II-SEM', 'II-sem'), ('III-SEM', 'III-sem'), ('IV-SEM', 'IV-sem'), ('V-SEM', 'V-sem'), ('VI-SEM', 'VI-sem'), ('VII-SEM', 'VII-sem'), ('VIII-SEM', 'VIII-sem')], max_length=100)),
                ('subject_name', models.CharField(blank=True, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
